const StyleDictionary = require('style-dictionary');

// Definimos fontConfig directamente aquí ya que style-dictionary no puede importar TS
const fontConfig = {
  LexendDeca: {
    regular: 'LexendDeca-Regular',
    medium: 'LexendDeca-Medium',
    semiBold: 'LexendDeca-SemiBold',
    bold: 'LexendDeca-Bold',
  },
};

StyleDictionary.registerFormat({
  name: 'typescript/module',
  formatter: function({ dictionary }) {
    const tokens = {
      colors: dictionary.tokens.color,
      spacing: dictionary.tokens.spacing,
      border: dictionary.tokens.border,
      typography: dictionary.tokens.typography,
    };

    return `// Generated by Style Dictionary
export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type Tokens = typeof tokens;`;
  }
});

StyleDictionary.registerTransform({
  name: 'name/font/family',
  type: 'value',
  matcher: token => token.attributes.category === 'typography' && token.attributes.type === 'fontFamily',
  transformer: token => {
    const [family, weight] = token.value.split('-');
    return weight ? fontConfig[family][weight.toLowerCase()] : fontConfig[family].regular;
  }
});

module.exports = {
  source: ["src/design-system/tokens/source/**/*.json"],
  platforms: {
    ts: {
      transformGroup: "js",
      transforms: [
        'name/font/family',
        'attribute/cti',
        'name/cti/pascal',
      ],
      buildPath: "src/design-system/tokens/generated/",
      files: [
        {
          destination: "tokens.ts",
          format: "typescript/module",
          options: {
            showFileHeader: false,
          }
        }
      ]
    }
  }
}; 